[package]
name = "movelings"
version = "0.1.0"
edition = "2021"
description = "Interactive Move programming language exercises"

[[bin]]
name = "movelings"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
colored = "2.0.0"
notify = "6.1.1"